import React from 'react'
import './Legal.css'

const Terms = () => {
    return (
        <div className='white-container container'>
            <h1 className='text-center py-5'>Website Terms and Conditions</h1>
            <h4>Terms and Conditions</h4>
            <p>Please read these terms and conditions carefully before using Our Service.</p>
            <h3>Interpretation and Definitions</h3>
            <h6>Interpretation</h6>
            <p>
                The words of which the initial letter is capitalized have 
                meanings defined under the following conditions. The following 
                definitions shall have the same meaning regardless of whether 
                they appear in singular or in plural.
            </p>
            <h6>Definitions</h6>
            <p>
                For the purposes of this Privacy Policy:
            </p>
            <ul className='definitions'>
                <li>
                    <p>
                        <strong>Account</strong> means a unique account created 
                        for You to access our Service or parts of our Service.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Company</strong> (referred to as either "the 
                        Company", "We", "Us" or "Our" in this Agreement) refers 
                        to LABQ CLINICAL DIAGNOSTICS LLC, 140 58TH ST. BLDG A, 
                        SUITE 3L BROOKLYN, NY 11220.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Cookies</strong> are small files that are placed 
                        on Your computer, mobile device or any other device by a 
                        website, containing the details of Your browsing history 
                        on that website among its many uses.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Country</strong> refers to: New York, United States
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Device</strong> means any device that can access 
                        the Service such as a computer, a cellphone or a digital 
                        tablet.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Personal Data</strong> is any information that relates to an 
                        identified or identifiable individual.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Service</strong> refers to the Website.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Service Provider</strong> means any natural or 
                        legal person who processes the data on behalf of the 
                        Company. It refers to third-party companies or individuals 
                        employed by the Company to facilitate the Service, to 
                        provide the Service on behalf of the Company, to perform 
                        services related to the Service or to assist the Company 
                        in analyzing how the Service is used.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Third-party Social Media Service</strong> refers 
                        to any website or any social network website through which 
                        a User can log in or create an account to use the Service.
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Usage Data</strong> refers to data collected 
                        automatically, either generated by the use of the Service 
                        or from the Service infrastructure itself (for example, 
                        the duration of a page visit).
                    </p>
                </li>
                <li>
                    <p>
                        <strong>Website</strong> refers to QCare, accessible 
                        from <a href='https://qcare.com'>https://qcare.com</a>
                    </p>
                </li>
                <li>
                    <p>
                        <strong>You</strong> means the individual accessing or 
                        using the Service, or the company, or other legal entity 
                        on behalf of which such individual is accessing or using 
                        the Service, as applicable.
                    </p>
                </li>
            </ul>
        </div>
    )
}

export default Terms